# Generated by Django 3.1.2 on 2020-10-29 17:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', max_length=500, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', max_length=500, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('archetype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CharacterCreator.archetype')),
            ],
        ),
        migrations.CreateModel(
            name='Dice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('quantity', models.IntegerField(default=1)),
                ('sides', models.IntegerField(default=2)),
                ('offset', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', max_length=500, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('dice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CharacterCreator.dice')),
                ('nextevent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NextEvent', to='CharacterCreator.event')),
                ('rerollevent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RerollEvent', to='CharacterCreator.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventRoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField(null=True)),
                ('outcome', models.CharField(max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('npc', models.CharField(max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('rerollcount', models.IntegerField(default=1)),
                ('selection', models.BooleanField(default=False)),
                ('mainevent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MainEvent', to='CharacterCreator.event')),
                ('rollevent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RollEvent', to='CharacterCreator.event')),
            ],
        ),
        migrations.CreateModel(
            name='Pointpool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', max_length=500, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', max_length=500, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='TraitCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', max_length=500, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', max_length=500, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('direction', models.CharField(choices=[('I', 'increasing'), ('D', 'decreasing')], default='I', max_length=100)),
                ('cost', models.IntegerField(default=0)),
                ('tier', models.IntegerField(choices=[(0, 'add'), (1, 'multiply'), (2, 'double'), (3, 'triple'), (4, 'quadruple'), (5, 'quintuple'), (6, 'sextuple'), (7, 'septuple'), (8, 'octuple'), (9, 'nonuple'), (10, 'decuple')], default=0)),
                ('purchase', models.IntegerField(default=0)),
                ('archetype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CharacterCreator.archetype')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CharacterCreator.traitcategory')),
                ('pointpool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CharacterCreator.pointpool')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CharacterCreator.role')),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', max_length=500, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('direction', models.CharField(choices=[('I', 'increasing'), ('D', 'decreasing')], default='I', max_length=100)),
                ('cost', models.IntegerField(default=0)),
                ('tier', models.IntegerField(choices=[(0, 'add'), (1, 'multiply'), (2, 'double'), (3, 'triple'), (4, 'quadruple'), (5, 'quintuple'), (6, 'sextuple'), (7, 'septuple'), (8, 'octuple'), (9, 'nonuple'), (10, 'decuple')], default=0)),
                ('type', models.CharField(choices=[('I', 'independent'), ('D', 'dependent')], default='I', max_length=100)),
                ('purchase', models.IntegerField(default=0)),
                ('archetype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CharacterCreator.archetype')),
                ('pointpool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CharacterCreator.pointpool')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CharacterCreator.role')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', max_length=500, validators=[django.core.validators.MinLengthValidator(1)])),
                ('direction', models.CharField(choices=[('I', 'increasing'), ('D', 'decreasing')], default='I', max_length=100)),
                ('cost', models.IntegerField(default=0)),
                ('tier', models.IntegerField(choices=[(0, 'add'), (1, 'multiply'), (2, 'double'), (3, 'triple'), (4, 'quadruple'), (5, 'quintuple'), (6, 'sextuple'), (7, 'septuple'), (8, 'octuple'), (9, 'nonuple'), (10, 'decuple')], default=0)),
                ('purchase', models.IntegerField(default=0)),
                ('archetype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CharacterCreator.archetype')),
                ('pointpool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CharacterCreator.pointpool')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CharacterCreator.role')),
                ('statistic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CharacterCreator.statistic')),
            ],
        ),
        migrations.CreateModel(
            name='NPCEventRoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PlayerCharacter', to='CharacterCreator.character')),
                ('eventroll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CharacterCreator.eventroll')),
                ('npc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NPC', to='CharacterCreator.character')),
            ],
        ),
        migrations.CreateModel(
            name='NPCEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CurrentNPCEvent', to='CharacterCreator.event')),
                ('next', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NextNPCEvent', to='CharacterCreator.event')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterTrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.IntegerField(default=0)),
                ('minimum', models.IntegerField(null=True)),
                ('maximum', models.IntegerField(null=True)),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CharacterCreator.character')),
                ('trait', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CharacterCreator.trait')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.IntegerField(default=0)),
                ('minimum', models.IntegerField(null=True)),
                ('maximum', models.IntegerField(null=True)),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CharacterCreator.character')),
                ('statistic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CharacterCreator.statistic')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.IntegerField(default=0)),
                ('minimum', models.IntegerField(null=True)),
                ('maximum', models.IntegerField(null=True)),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CharacterCreator.character')),
                ('skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CharacterCreator.skill')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterPointpool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CharacterCreator.character')),
                ('pointpool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CharacterCreator.pointpool')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterEventRoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CharacterCreator.character')),
                ('eventroll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CharacterCreator.eventroll')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CharacterCreator.role'),
        ),
    ]
